### ISSUE TITLE
xamarin port

### ISSUE THREAD

**Issue by kibotu** [ArchitShah248/CalendarDateRangePicker#10]
just letting you know that i've ported your awesome lib to xamarin

https://github.com/kibotu/Xamarin.Awesome.Calendar

and uploaded a nuget

https://www.nuget.org/packages/Xamarin.Awesome.Calendar/1.1.1

stay awesome!

**Comment by ArchitShah248** [comment]
That's awesome man..!! Keep up the good work. 
Can I add your nuget link into my readme.md?

**Comment by kibotu** [comment]
of course: https://www.nuget.org/packages/Xamarin.Awesome.Calendar/
