### ISSUE TITLE
Past Dates Enable

### ISSUE THREAD

**Issue by FahanBakht** [ArchitShah248/CalendarDateRangePicker#16]
Hi Archit Shah, Thanks for this great library but i am facing a problem i need to enable past dates how can i achieve it ? , is there any way ?
Thanks

**Comment by vinsbhat** [comment]
Hi Archit, Even I need to add a filter for past dates. I didnt find a way to enable past dates in your library. Please let me know how to achieve it.

**Comment by ArchitShah248** [comment]
@FahanBakht @vinsbhat Please refer #4 to satisfy your needs. 
Happy coding..!!
