### ISSUE TITLE
How to free range selection ?

### ISSUE THREAD

**Issue by PaolinoAngeletti** [ArchitShah248/CalendarDateRangePicker#18]
today is the 17th of September, and if I run the library, the first selectable day is 17 Sept.
How can I free the selection ? 
If I want select ' 01/01/2000 ' to ' 31/12/2059 ' , for example..

**Comment by ArchitShah248** [comment]
@PaolinoAngeletti I believe you are asking to enable past dates?

**Comment by mikemasam** [comment]
Yes Yes, even me i can't select past hours.

**Comment by ArchitShah248** [comment]
@PaolinoAngeletti @mikemasam Past date selection feature has been added in #17. I will release new version shortly on maven.
