### ISSUE TITLE
How can create a hijra calendar like this

### ISSUE THREAD

**Issue by Arunpayyeri** [ArchitShah248/CalendarDateRangePicker#2]
Sir. Can you please develop a hijri calendar like this date range picker. I think there is no library available in hijri. This is only a suggestion. Thanks for developing this picker. How can be develop hijra calendar

**Comment by ArchitShah248** [comment]
Thanks @Arunpayyeri!! I am sorry but I don't have much knowledge about it. But it is definitely possible to develop Hijra calendar once we have its understanding.
