### ISSUE TITLE
open the calendar on the current month.

### ISSUE THREAD

**Issue by lawrencecsfrancisco** [ArchitShah248/CalendarDateRangePicker#20]
Hi i'm currently using this code :  

```
    Calendar startMonth = Calendar.getInstance();
        startMonth.add(Calendar.MONTH, -4);
        Calendar endMonth = Calendar.getInstance();
        endMonth.add(Calendar.MONTH, 0);
        calendar.setVisibleMonthRange(startMonth,endMonth);

```

so the my current date is september where it limits the user to go more than september.
my problem is i want to start the calendar to my current month.
whenever i try to open the calendar with the code above, it opens the calendar in june where the user need to navigate all the way to september to get the current month.

it would be better if i can open the calendar that is already in september / current month so that the user wont need to navigate from june to september. i hope you get it. thanks!

i hope you can fix this. thanks!

**Comment by ArchitShah248** [comment]
@lawrencecsfrancisco Thank you for bringing this requirement. I will surely add this feature into next release.

**Comment by ArchitShah248** [comment]
Feature added in V1.1.4. I will release soon.
