### ISSUE TITLE
Change the language of the days

### ISSUE THREAD

**Issue by alon464** [ArchitShah248/CalendarDateRangePicker#21]
How can I change the days that displayed into German?? I can't find this option..

**Comment by ArchitShah248** [comment]
@alon464 Sorry for the late reply. You can change the days language by putting this string values in app strings.xml
<string name="cdrp_mon">Mon</string>
    <string name="cdrp_tue">Tue</string>
    <string name="cdrp_wed">Wed</string>
    <string name="cdrp_thu">Thu</string>
    <string name="cdrp_fri">Fri</string>
    <string name="cdrp_sat">Sat</string>
    <string name="cdrp_sun">Sun</string>

Happy coding!

**Comment by alon464** [comment]
Thank you very much, do yiu know maybe how can I add to the  
dependencies in the Gradle file the dependency I forked from your  
Master? Like your com.archit.calendar...

Best wishes
Alon


Zitat von Archit Shah <notifications@github.com>:

**Comment by ggn22g** [comment]
> ```
>  <string name="cdrp_mon">Mon</string>
>     <string name="cdrp_tue">Tue</string>
>     <string name="cdrp_wed">Wed</string>
>     <string name="cdrp_thu">Thu</string>
>     <string name="cdrp_fri">Fri</string>
>     <string name="cdrp_sat">Sat</string>
>     <string name="cdrp_sun">Sun</string>
> ```

Thank you so much.  Appreciated.
