### ISSUE TITLE
Disable future dates

### ISSUE THREAD

**Issue by lawrencecsfrancisco** [ArchitShah248/CalendarDateRangePicker#22]
Hi, good day.

Your library is splendid and beautiful, however may I ask if I can disable the future dates? like the user can only select from current date until to its past 4 months. I hope it's possible. thanks!

**Comment by ArchitShah248** [comment]
@lawrencecsfrancisco Yet date wise activation is not supported in current release however you can restrict to month wise activation. 

Calendar startMonth = Calendar.getInstance();
startMonth.add(Calendar.MONTH, -4);
Calendar endMonth = Calendar.getInstance();

calendar.setVisibleMonthRange(startMonth,endMonth);

**Comment by osamai2006** [comment]
@ArchitShah248  i did this but the dates are disabled in the past !!!

**Comment by Ricardo-A** [comment]
you also need to set enable_past_date to true

**Comment by binhbk230** [comment]
Hi, I already disable future date by this way, but when calendar showing it show start date in the last. I wanna it show default is end date. How to do it?
