### ISSUE TITLE
Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml

### ISSUE THREAD

**Issue by mangeshsambare** [ArchitShah248/CalendarDateRangePicker#23]
Hi Archit,

I found one issue. In my AndroidManifest.xml file I do : 
`<application
        android:allowBackup="false"
        android:icon="@drawable/ic_launcher_icon"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        tools:ignore="GoogleAppIndexingWarning">
</application>
`

After this I am trying to run application code. I got this error :

`Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:38:9-36
	is also present at [com.archit.calendar:awesome-calendar:1.1.3] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:36:5-212:19 to override.`

In my application I do not want to allow backup. So that's why I make it as false. SO please look into this & let me know after solving this problem.

Thanks!

**Comment by ArchitShah248** [comment]
@mangeshsambare Please refer below link
https://stackoverflow.com/questions/46934387/attribute-applicationallowbackup-value-false-from-androidmanifest-xml-is-also

Hope your problem gets solved. Happy coding !!
