### ISSUE TITLE
unable to change text size of calendar month, title or days

### ISSUE THREAD

**Issue by TechyM** [ArchitShah248/CalendarDateRangePicker#24]
<com.archit.calendardaterangepicker.customviews.DateRangeCalendarView
            android:id="@+id/calendar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            custom:calendar_tag="Test"
            custom:disable_date_color="@color/gray_transparent"
            custom:enable_past_date="false"
            custom:header_bg="@color/border_grey"
            custom:range_color="@color/range_bg_color_app"
            custom:selected_date_circle_color="@color/selected_date_circle_color_app"
            custom:title_color="@color/calendar_header_title"
            custom:editable="true"
            custom:week_offset="1"
            custom:week_color="@color/black"
            custom:text_size_title="16sp"
            custom:text_size_week="14sp"
            custom:text_size_date="14sp"
            />

There is no difference in calendar size inspite of using text_style_title, text_size_week or text_size_date

**Comment by ArchitShah248** [comment]
@TechyM Thanks for pointing out this issue. The issue has been solved in https://github.com/ArchitShah248/CalendarDateRangePicker/commit/33f950c7c572179b630bd92292def7552b5cd29a.

Happy coding..!!!
