### ISSUE TITLE
Enable selected past date!!!

### ISSUE THREAD

**Issue by skaciroy92** [ArchitShah248/CalendarDateRangePicker#26]
Hi guys,
Your library is a great lib. So cool & nice, i'm using it in my app. However i got an issue with "enable selected past date" feature.
I have added attribute:
- custom:enable_past_date="true"
in resource xml file, but i can't select past date on the screen. Please help to check or resolve it, many thanks..

https://imgur.com/a/1G4fDe6

**Comment by ArchitShah248** [comment]
@skaciroy92 Can you please try it again? It's working fine at our end.

**Comment by JorikFat** [comment]
Hi, have this trouble too.
What namespace need to use?

**Comment by ArchitShah248** [comment]
Added new feature to set `selectableDateRange(startDate, endDate)`. Cheers!!
