### ISSUE TITLE
support RTL

### ISSUE THREAD

**Issue by khaledkhj** [ArchitShah248/CalendarDateRangePicker#27]
Thanks for the great work!

any support to rtl apps?
The ui is missed up on rtl apps :)

Thank you.

![screenshot_20181112-211505](https://user-images.githubusercontent.com/2294141/48349789-33162a00-e6c0-11e8-9c2c-7a5323bbb473.jpg)

**Comment by ArchitShah248** [comment]
@khaledkhj  Due to some medical emergency couldn't reply to soon. I would love to give support for RTL. However, because of time constraint, it will take some time. Meanwhile, you can also contribute to that. Your help will be appreciated.

**Comment by ramyassaf** [comment]
Hi ArchitShah,

I'm using your awesome calendar in one of my project that has RTL, everything is working fine except of one thing in the time picker after you select the date: the button Cancel and Done are overlapped and both are on the right of the screen. (check screenshot attached for more info)
I would like to contibute but I couldn't find where is the file to update the xml and make the cancel layout_gravity at the start and done layout gravity at the end.
![Screenshot_1585222538](https://user-images.githubusercontent.com/4056602/77642937-261d7200-6f67-11ea-9910-42018b5d19bf.png)

**Comment by ramyassaf** [comment]
Thank you for merging my commit to the master branch, now the done button will be on the left with RTL languages.

**Comment by farahetmeh** [comment]
@DateRangeMonthView class replace "makeAsSelectedDate" function with :
 
    private void makeAsSelectedDate(final DayContainer container, @DateRangeCalendarManager.RANGE_TYPE final int stripType) {
        final RelativeLayout.LayoutParams layoutParams = (RelativeLayout.LayoutParams) container.strip.getLayoutParams();

        final Calendar minDate = dateRangeCalendarManager.getMinSelectedDate();
        final Calendar maxDate = dateRangeCalendarManager.getMaxSelectedDate();

        boolean isRightToLeft = getResources().getBoolean(R.bool.is_right_to_left);
        
        if (stripType == DateRangeCalendarManager.RANGE_TYPE.START_DATE && maxDate != null &&
                minDate.compareTo(maxDate) != 0) {
            if (isRightToLeft){
                final Drawable mDrawable = ContextCompat.getDrawable(getContext(), R.drawable.range_bg_right);
                mDrawable.setColorFilter(new PorterDuffColorFilter(calendarStyleAttr.getRangeStripColor(), FILTER_MODE));
                container.strip.setBackground(mDrawable);
                layoutParams.setMargins(0, 0, 20, 0);
            }else{
                final Drawable mDrawable = ContextCompat.getDrawable(getContext(), R.drawable.range_bg_left);
                mDrawable.setColorFilter(new PorterDuffColorFilter(calendarStyleAttr.getRangeStripColor(), FILTER_MODE));
                container.strip.setBackground(mDrawable);
                layoutParams.setMargins(20, 0, 0, 0);
            }
            

            
        } else if (stripType == DateRangeCalendarManager.RANGE_TYPE.LAST_DATE) {
            if (isRightToLeft) {
                final Drawable mDrawable = ContextCompat.getDrawable(getContext(), R.drawable.range_bg_left);
                mDrawable.setColorFilter(new PorterDuffColorFilter(calendarStyleAttr.getRangeStripColor(), FILTER_MODE));
                container.strip.setBackground(mDrawable);
                layoutParams.setMargins(20, 0, 0, 0);
            }else{
                final Drawable mDrawable = ContextCompat.getDrawable(getContext(), R.drawable.range_bg_right);
                mDrawable.setColorFilter(new PorterDuffColorFilter(calendarStyleAttr.getRangeStripColor(), FILTER_MODE));
                container.strip.setBackground(mDrawable);
                layoutParams.setMargins(0, 0, 20, 0);
            }
        } else {
            container.strip.setBackgroundColor(Color.TRANSPARENT);
            layoutParams.setMargins(0, 0, 0, 0);
        }
        container.strip.setLayoutParams(layoutParams);
        final Drawable mDrawable = ContextCompat.getDrawable(getContext(), R.drawable.green_circle);
        mDrawable.setColorFilter(new PorterDuffColorFilter(calendarStyleAttr.getSelectedDateCircleColor(), FILTER_MODE));
        container.tvDate.setBackground(mDrawable);
        container.rootView.setBackgroundColor(Color.TRANSPARENT);
        container.tvDate.setTextColor(calendarStyleAttr.getSelectedDateColor());
        container.rootView.setVisibility(VISIBLE);
        container.rootView.setOnClickListener(dayClickListener);
    }

and add isrighttoleft file to values-ldrtl folder with the following content 
<?xml version="1.0" encoding="utf-8"?>
<resources>
<bool name="is_right_to_left">true</bool>
</resources> 

and add isrighttoleft file to values folder with the following content 
<?xml version="1.0" encoding="utf-8"?>
<resources>
<bool name="is_right_to_left">false</bool>
</resources>

**Comment by ArchitShah248** [comment]
Fixed in V2.0.0. Happy coding!
