### ISSUE TITLE
Add listener for single date selection

### ISSUE THREAD

**Issue by alterpie** [ArchitShah248/CalendarDateRangePicker#3]
Hi Archit! Very nice widget! One thing though, it would we very convenient to have a callback for single date selection.

**Comment by ArchitShah248** [comment]
Thanks @alterpie . I will surely add this callback as soon as possible.

**Comment by ArchitShah248** [comment]
#3 Resolved in [ Commit#   f18fcdf86cc72c794245b5e7272f7bcd7e3bd39f](https://github.com/ArchitShah248/CalendarDateRangePicker/commit/f18fcdf86cc72c794245b5e7272f7bcd7e3bd39f)
