### ISSUE TITLE
How can i set current day circle ? Please help me sir

### ISSUE THREAD

**Issue by hankury** [ArchitShah248/CalendarDateRangePicker#36]

**Comment by ArchitShah248** [comment]
@hankury : Sorry for the late reply.
Please try below code snippet.
```
Calendar today = Calendar.getInstance();
calendar.setVisibleMonthRange(today,today);
```
I hope you questioned is answred correctly.
Happy coding!! :)

**Comment by umanggoyal89** [comment]
@ArchitShah248 For displaying current date as selected we will use ```setSelectedDateRange``` method not ```setVisibleMonthRange```
```
   Calendar today = Calendar.getInstance();
        calendar.setSelectedDateRange(today,today);
```
