### ISSUE TITLE
How to set visible another month/year?

### ISSUE THREAD

**Issue by blopez** [ArchitShah248/CalendarDateRangePicker#37]
As of today, February 2019 is set as visible month when loading the calendar, and that's fine. I have a functionality where I expand the visible month ranges (e.g. from January 1980 to February 2019). For this, I use:
`calendar.setVisibleMonthRange(startDate, endDate)`

The problem here is that doing this, the current visible month on the UI is January 1980 (let's say, the first month available within the wide range of visible months, from 1980 to 2019). After setting this visibleMonthRange 1980-2019, I want to view for instance September 2016, but I cannot find any function that changes the current visible month and year.

I've tried setSelectedDateRange (which works fine but does not change the user interface), also setCurrentMonth that only changes the month but not the year. 

How can I achieve this?

**Comment by ArchitShah248** [comment]
@blopez You can achieve that by:

`Calendar current = Calendar.getInstance();calendar.setCurrentMonth(current);`
