### ISSUE TITLE
setCurrentMonth does not check for the year. 

### ISSUE THREAD

**Issue by proguyer** [ArchitShah248/CalendarDateRangePicker#47]
I have set valid months up to 1 year behind. 
When i want to set the current month, however, setCurrentMonth selects the first month which belongs to the previous year. 

I went to further check on the code, i found the current setCurrentMonth does not check for the year. 

The library looks really good thou.

**Comment by ArchitShah248** [comment]
@proguyer : Thanks for pointing out the issue. Issue has been fixed.
