### ISSUE TITLE
Disable Range selector? 

### ISSUE THREAD

**Issue by melatgenius** [ArchitShah248/CalendarDateRangePicker#50]
is there a way to disable the range date selector? I just want the user to be able to select 1 date

**Comment by melatgenius** [comment]
@ArchitShah248

**Comment by Ricardo-A** [comment]
Already made a pull request with the feature, just wait a little for the author to accept ;)

**Comment by ArchitShah248** [comment]
Date selection mode is added in V2.0.0. Cheers!!

Happy coding!
