### ISSUE TITLE
setCurrentMonth still not working properly

### ISSUE THREAD

**Issue by aliakkawi** [ArchitShah248/CalendarDateRangePicker#52]
Hello,
i am facing the same issue as for issue #47,
here is my code:
Calendar lastYear = Calendar.getInstance();
        lastYear.add(Calendar.YEAR, -1);
        Calendar todayCalendar = Calendar.getInstance();

        calendar_view.setVisibleMonthRange(lastYear, todayCalendar);
        calendar_view.setCurrentMonth(todayCalendar);
it displays June 2018

**Comment by ArchitShah248** [comment]
Thanks for using this library. The issue has been fixed.
