### ISSUE TITLE
Is v1.1.5 going to be publicly available soon?

### ISSUE THREAD

**Issue by ogartaganis** [ArchitShah248/CalendarDateRangePicker#56]
I'm looking for the fix of "setCurrentMonth" [#52](https://github.com/ArchitShah248/CalendarDateRangePicker/issues/52) and [#47](https://github.com/ArchitShah248/CalendarDateRangePicker/issues/47) but so far the version without the fix (v.1.1.4) is the latest one available!

**Comment by ArchitShah248** [comment]
@ogartaganis : Right away! Thanks for reminding.

Happy coding!!

**Comment by ogartaganis** [comment]
Thanks man, works perfectly! 🥇
