### ISSUE TITLE
UI glitch with range selection

### ISSUE THREAD

**Issue by robertoestivill** [ArchitShah248/CalendarDateRangePicker#6]
When the range starts and ends in the same day (double click in the same day) the selected UI looks funny.

<img width="285" alt="screen shot 2018-07-16 at 6 52 34 pm" src="https://user-images.githubusercontent.com/3728545/42772039-6de6a992-8929-11e8-8174-7c087b49299c.png">

**Comment by ArchitShah248** [comment]
Thank you @robertoestivill for pointing out this issue. It has been fixed in V1.1.1. 
Happy coding !!

**Comment by robertoestivill** [comment]
Wow that was a speedy fix! Thanks man!
