### ISSUE TITLE
How to select previous year date

### ISSUE THREAD

**Issue by AdilSattar1233** [ArchitShah248/CalendarDateRangePicker#67]
Unable to select past year dates

**Comment by ArchitShah248** [comment]
Hi @AdilSattar1233 , you need to first set visible months by using `calendar.setVisibleMonthRange(startMonth, endMonth);`. I hope it helps.

Happy coding!

**Comment by AdilSattar1233** [comment]
Bro kindly guide I appreciate your work. Kindly tell me what is the
benefits to make library for others. GitHub pay you or some other earning
source apply ..kindly guide me what is the earning method on github
