### ISSUE TITLE
DateRange Listener not working

### ISSUE THREAD

**Issue by unaisulhadi** [ArchitShah248/CalendarDateRangePicker#68]
setCalendarListener(new DateRangeCalendarView.CalendarListener() {}); not working in version 1.1.6
when changes to version 1.1.5 setSelectableDateRange not working ?

**Comment by ArchitShah248** [comment]
Hi @unaisulhadi , `setCalendarListener` is working in V1.1.6. Kindly check the example app-([MainActivity.java](https://github.com/ArchitShah248/CalendarDateRangePicker/blob/master/app/src/main/java/com/archit/calendardaterangepickerdemo/MainActivity.java)). 
`setSelectableDateRange` is not available in V1.1.5.

Happy coding!

**Comment by unaisulhadi** [comment]
Take a look bro, Its not working for me

**Comment by ArchitShah248** [comment]
It's working here. What issues are you facing?

**Comment by ArchitShah248** [comment]
@unaisulhadi : I have fixed `CalendarListener` accessibility issue in V1.1.7. Thanks for pointing out.

**Comment by unaisulhadi** [comment]
You are welcome
