### ISSUE TITLE
issue with setSelectableDateRange

### ISSUE THREAD

**Issue by RnldStephen** [ArchitShah248/CalendarDateRangePicker#72]
I set the date range from 1/1/2020 to the current date.
But if i select  today's date it give an exception saying selected date range cannot exceed  selectable date range.

**Comment by ArchitShah248** [comment]
Hi @RnldStephen , can you please paste your code here so that I can reproduce the same issue?

**Comment by RnldStephen** [comment]
`  Calendar endrange = Calendar.getInstance();
   Calendar startRange = Calendar.getInstance();
   SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
                   
 try {
                        Date df = df.parse("01-01-2020");
                        startRange.setTime(df)
               cal.setSelectableDateRange(startRange ,endrange);
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }   `

So the start date is 1/1/2020 and the end date would be the current date . Let's say that the current date is April 17 2020. So if I click on April 17 2020 in the calender it crashes with the error that the selected date is higher than the allowed range


But the dates after 17 are disabled and not clickable that works fine

**Comment by ArchitShah248** [comment]
Thanks @RnldStephen , I am able to reproduce the issue. It'll be fixed in V1.1.7.

**Comment by RnldStephen** [comment]
When will you be able to do it? If it is a shirt time then I will wait for
you to do it before I release my app

**Comment by ArchitShah248** [comment]
Yes, V1.1.7 has been published. You can use it in your application. Test it and let me know your feedback.

Happy coding!!

**Comment by RnldStephen** [comment]
Thank you. Will try and get back to you as soon as possible

**Comment by RnldStephen** [comment]
Works like a charm now. Thank you

Regards
Ronald

**Comment by ArchitShah248** [comment]
Thanks @RnldStephen  for the quick validation.
